/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109772-gc56f5be678-20230208"
#endif /* AVUTIL_FFVERSION_H */
